import path from "node:path";
import { Chess } from "chess.js";

/**
 * Shared low-level helpers used across modules. Anything that was being
 * reimplemented in multiple files should live here.
 */

const MATE_BASE = 10000;
const MATE_PLY_WEIGHT = 10;

/**
 * Project a PV entry's {cp, mate} score down to a single centipawn-equivalent
 * scalar. Mate scores dominate cp values; faster mates produce larger
 * magnitudes. Returns null when both fields are missing.
 *
 *   cp=+120, mate=null  →  120
 *   cp=null, mate=+3    →  +9970   (10000 - 3*10)
 *   cp=null, mate=-2    →  -9980   (-10000 - (-2)*10 = -9980)
 *
 * @param {{cp?: number|null, mate?: number|null}|null|undefined} pv
 * @returns {number|null}
 */
export function pvScalar(pv) {
  if (!pv) return null;
  if (pv.mate != null) {
    return pv.mate > 0
      ? MATE_BASE - pv.mate * MATE_PLY_WEIGHT
      : -MATE_BASE - pv.mate * MATE_PLY_WEIGHT;
  }
  if (pv.cp != null) return pv.cp;
  return null;
}

/**
 * Convert a UCI move to SAN against a starting FEN. Returns null when the
 * move is illegal or any of the inputs are missing — callers fall back to
 * the raw UCI string.
 */
export function uciToSan(fen, uci) {
  if (!fen || !uci) return null;
  try {
    const board = new Chess(fen);
    const m = board.move({
      from: uci.slice(0, 2),
      to: uci.slice(2, 4),
      promotion: uci.length > 4 ? uci[4] : undefined,
    });
    return m?.san ?? null;
  } catch {
    return null;
  }
}

/**
 * Convert a UCI PV (array of UCI strings) to an array of SAN strings by
 * replaying each move sequentially against a chess.js board. Stops early
 * on the first illegal move or up to maxPlies. Previously duplicated in
 * challenge.js and summary.js.
 *
 * @param {string|null} fen         starting position FEN
 * @param {string[]|undefined} uciPv  UCI move array
 * @param {number} [maxPlies]       maximum moves to convert
 * @returns {string[]}
 */
export function uciPvToSan(fen, uciPv, maxPlies) {
  const out = [];
  if (!fen || !Array.isArray(uciPv)) return out;
  const board = new Chess(fen);
  for (let i = 0; i < Math.min(uciPv.length, maxPlies); i++) {
    const u = uciPv[i];
    try {
      const m = board.move({
        from: u.slice(0, 2),
        to: u.slice(2, 4),
        promotion: u.length > 4 ? u[4] : undefined,
      });
      if (!m) break;
      out.push(m.san);
    } catch {
      break;
    }
  }
  return out;
}

const HTML_ESCAPES = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};

/**
 * Escape a string for safe HTML interpolation (attributes and text content).
 */
export function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => HTML_ESCAPES[c]);
}

/**
 * Escape a string for safe XML/SSML interpolation. Same rules as escapeHtml
 * but uses &apos; (the XML-spec name) instead of &#39;.
 */
export function escapeXml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Convert a path to forward-slash form so manifests are portable across
 * platforms even when written on Windows.
 */
export function toForwardSlash(p) {
  return p.split(path.sep).join("/");
}

/**
 * Slugify an arbitrary string for safe use as a filename segment. Strips
 * path separators (incl. `..`), keeps alnum + dash + underscore + dot, and
 * collapses runs of `-`. Never returns an empty string.
 *
 * Defense-in-depth: shot.id is currently generated by trusted code, but the
 * narration JSON is user-editable and lands in `${shot.id}.html|.wav|.png`
 * filenames. Slugifying at the filesystem boundary keeps a hand-edited
 * `"id": "../../etc/passwd"` from escaping the output directory.
 */
export function slugifyId(id) {
  const s = String(id ?? "")
    .replace(/[\\/]/g, "-")
    .replace(/\.\.+/g, "-")
    .replace(/[^A-Za-z0-9._-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
  return s.length > 0 ? s : "shot";
}

/**
 * Parse a CLI numeric flag and validate it's a positive integer. Use for
 * --depth / --multipv / --opening-plies / --key-depth / --position-depth.
 * Rejects NaN, negatives, zero, and floats.
 *
 * @param {string} name        flag name for the error message
 * @param {string|undefined} raw  value as passed on the command line
 * @param {number} fallback    used when raw is null/undefined
 * @returns {number}
 */
export function assertPositiveInt(name, raw, fallback) {
  if (raw == null) return fallback;
  if (!/^-?\d+$/.test(String(raw).trim())) {
    throw new Error(`${name}: expected a positive integer (got ${JSON.stringify(raw)})`);
  }
  const n = parseInt(raw, 10);
  if (!Number.isInteger(n) || n < 1) {
    throw new Error(`${name}: expected a positive integer (got ${JSON.stringify(raw)})`);
  }
  return n;
}

/**
 * Parse a CLI signed-integer flag (e.g. --rate, which accepts negatives).
 * Returns the fallback when raw is null/undefined.
 */
export function assertSignedInt(name, raw, fallback) {
  if (raw == null) return fallback;
  if (!/^-?\d+$/.test(String(raw).trim())) {
    throw new Error(`${name}: expected an integer (got ${JSON.stringify(raw)})`);
  }
  return parseInt(raw, 10);
}

/**
 * Lightweight registry of long-lived child processes so the CLI's signal
 * handler can terminate them on Ctrl+C. Plain Set, no events — modules just
 * register the child after spawning and the entry is removed on exit.
 */
export const childProcesses = new Set();

/**
 * Register a child_process so the CLI signal handler can clean it up.
 * Returns the same child so calls can be inlined: `trackChild(spawn(...))`.
 */
export function trackChild(child) {
  if (!child) return child;
  childProcesses.add(child);
  child.once("exit", () => childProcesses.delete(child));
  return child;
}
